package main

import (
	"crypto/tls"
	"fmt"
	"path/filepath"

	"github.com/nxshock/simplelog"
)

type Config struct {
	// Log level
	LogLevel simplelog.LogLevel

	// Path to TLS-certificates generated by Certbot
	TlsKeysDir string

	// TLS listen address
	TlsListenAddr string

	// HTTP listen address
	HttpListenAddr string

	// Map of hostname -> redirect URL
	TLS map[string]string

	// Acme path
	AcmeChallengePath string

	// Parsed list of servers
	proxyRules HostMapping

	// loaded TLS keys
	tlsConfig *tls.Config
}

func (c *Config) initTls() error {
	logger.Debug("Loading TLS keys")

	c.tlsConfig = new(tls.Config)

	for hostName := range c.proxyRules {
		logger.Debug("reading tls key for host", hostName)

		certFilePath := filepath.Join(c.TlsKeysDir, hostName, defaultCertFileName)
		keyFilePath := filepath.Join(c.TlsKeysDir, hostName, defaultKeyFileName)

		cert, err := tls.LoadX509KeyPair(certFilePath, keyFilePath)
		if err != nil {
			return fmt.Errorf("read tls files error: %v", err)
		}

		c.tlsConfig.Certificates = append(c.tlsConfig.Certificates, cert)
	}

	return nil
}
